apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: apache
   labels:
     app: apache
spec:
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: ameng/php7-apache2
        name: apache
        env:
        - name: DB_HOST
          value: mysql-service.default.svc.cluster.local
        - name: DB_NAME
          value: demo
        - name: DB_USER
          value: root
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
