apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: magento2
   labels:
   app: magento2
spec:
  strategy:
     type: Recreate
  template:
  metadata:
  labels:
    app: magento2
    tier: frontend
 spec:
   containers:
   - image: alexcheng/magento2
     name: magento2
   env:
   - name: MAGENTO_DB_HOST
     value: magento2-mysql
   - name: MAGENTO_DB_PASSWORD
     valueFrom:
      secretKeyRef:
        name: mysql-pass
        key: password
   ports:
   - containerPort: 80
     name: magento2
