apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: magento2-mysql
  labels:
    app: magento2-mysql
spec:
  template:
    metadata:
      labels:
        app: magento2-mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
